name: club_huandoy
description: "App Club Deportivo Integral Huandoy"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.1
  cloud_functions: ^5.6.2
  
  
  http: ^1.1.0
  intl: ^0.20.2
  url_launcher: ^6.2.5

  geolocator: ^10.1.0
  geocoding: ^3.0.0

  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2

  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_datetime_picker_plus: ^2.2.0
  uuid: ^4.3.3

  webview_flutter: ^4.13.0
  
  flutter_tesseract_ocr: ^0.4.30
  image: ^4.1.3
  
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/Logo_huandoy.png